# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Survey Science in Tucson
email: surveyastronomylunch@list.arizona.edu
description: > # this means to ignore newlines until "baseurl:"
  The Tucson Survey Science group discussions take place every other Tuesday at noon in Steward N305
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  

# Build settings
markdown: kramdown
future: TRUE
